author: Ефимов Д.С.
copyright: "2026"
execute:
    execute_notebooks: force
sphinx:
    config:
        language: ru
        html_static_path: ["static"]
        html_css_files: ["custom.css"]

        togglebutton_hint: "Подробнее" 
        
        html_theme_options:
            use_download_button: false
            repository_url: https://github.com/dsefimov/spatial-python
            repository_branch: main
            path_to_docs: materials
            launch_buttons:
                colab_url: "https://colab.research.google.com"
            logo:
                text: "Введение в Python: основы синтаксиса"
                image_light: materials/static/logo.svg
                image_dark: materials/static/logo.svg
